
foreground = white;
background = black;
font = Misc Fixed;
	
directory to choose music from = /home/bdr;
logo2 directory = /home/bdr/.config/graphite/logo2.png;
logo3 directory = /home/bdr/.config/graphite/logo3.png;
default playlist = /home/bdr/.config/graphite/playlists/graphite.pl;	
send notifs on song play = 0;

dir x = 0;
dir y = 215;
play x = 35;
play y = 215;
vol x = 105;
vol y = 215;
passed x = 230;
passed y = 222;
artist x = 0;
artist y = 13;
song x = 0;
song y = 0;
status x = 220;
status y = 0;

