#!/bin/python3

from tkinter import *
import tkinter as tk
import os, sys, time
from pathlib import Path

_sver = "0.1"

_bg = 'black'
_fg = 'white'
_fnt = ('Misc Fixed', 10)
_file_selected = True

try:
	with open(f'{Path.home()}/.config/soda/soda.conf', 'r') as f:
		for line in f:
			if '#' in line:
				pass
			elif ':' in line:
				key, val = (line.strip()).split(':')
				if key == 'bg':
					_bg = val
				elif key == 'fg':
					_fg = val
				elif key == 'font':
					font_name = val
				elif key == 'font_size':
					font_size = val
	_fnt = (f'{font_name}',int(font_size))
except Exception as NameError:
	print("config error")

_pad = Tk()
_pad.geometry("500x300")
_pad.title('soda')
_pad.config(background=str(_bg))

_sodatxt = r"""
          |
  __|  _ \   _` |  _` |
\__ \ (   | (   | (   |
____/\___/ \__,_|\__,_|
"""
_wth = 0
_hht = 0  
_fil = (str(*sys.argv[1:]))

if _fil == "":
	_file_selected = False
else:
	_file_selected = True

if _file_selected == True:
	_txt = Text(background=_bg,font=_fnt,highlightthickness=0.5,highlightcolor=_fg,highlightbackground=_fg,cursor='hand1',foreground=_fg,insertbackground=_fg,wrap="none")
	_txt_line, _txt_column = str(_txt.index("insert")).split('.')
	_txt.place(x=-1,y=-1,width=450,height=300)
	_txt.focus()

	_lne = Label(text=_txt_line,background=_fg,foreground=_bg,font=_fnt)
	_lne.place(x=400,y=40,width=50,height=10)
else:
	_soda_label = Label(background=_bg,font=_fnt,text=_sodatxt)
	_soda_label.place(x=228,y=5,width=138,height=52)
	
	#_pad2 = Tk()
	#_pad2.geometry("500x300")
	#_pad2.config(background=str(_bg))
	#_pad2.mainloop()

try:
	with open(_fil, 'rb') as f:
		for line in f:
			_txt.insert(END,line)
except Exception as FileError:
	pass
	# Put something here if you want, it triggers when you only type in soda without any args 
	# in your terminal

def save():
	global _fil
	_ent = Entry(background=_fg,foreground=_bg,font=_fnt,bd=0,relief='flat',highlightcolor=_fg)
	_ent.place(x=0,y=(_hht - 10),width=(len(_fil) + 48),height=11)
	_ent.insert(END,_fil)
	_ent.focus()
	def rsave():
		with open(_fil, 'w') as f:
			f.write(_txt.get(1.0, END))
			_txt.focus()
			_ent.destroy()
		return "break"
	_ent.bind('<Return>', lambda event: rsave())	

def upd():
	global _wth, _hht

	_wth = _pad.winfo_width()
	_hht = _pad.winfo_height()
	if _file_selected == True:
		_txt.place(x=-2,y=-2,width=_wth + 3,height=_hht + 3)
		_lne.place(x=(_wth - len(_txt_line)) - 48 ,y=(_hht - 10),width=50,height=10)
	else:
		_soda_label.place(x=(_wth - 138) / 2)


def recursion_upd():
	global _txt_line, _txt_column

	if _file_selected == True:
		_txt_line, _txt_column = str(_txt.index("insert")).split('.')
		_lne.config(text=f'{_txt_line}@{_txt_column}')

if _file_selected == True:
	_txt.bind('<Control-o>', lambda event: [save(), "break"][1])
_pad.bind('<Configure>', lambda event: upd())
_pad.bind('<KeyRelease>', lambda event: recursion_upd())
_pad.mainloop()
